name: 'Apply D1 Updates'
description: 'Apply incremental updates (upserts + deletes) to a Cloudflare D1 database'

inputs:
  database-name:
    description: 'D1 database name (e.g., geocoder-divisions-global)'
    required: true
  diff-path:
    description: 'Path to the diff SQL files (e.g., exports/diff)'
    required: true
  has-changes:
    description: 'Whether there are changes to apply'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Show diff stats
      if: inputs.has-changes == 'true'
      shell: bash
      run: |
        echo "Diff stats for ${{ inputs.database-name }}:"
        cat ${{ inputs.diff-path }}/stats.json

    - name: Apply upserts
      if: inputs.has-changes == 'true'
      shell: bash
      run: |
        echo "Applying upserts to ${{ inputs.database-name }}..."
        UPSERTS_FILE="${{ inputs.diff-path }}/upserts.sql"
        TOTAL_LINES=$(wc -l < "$UPSERTS_FILE")
        echo "Total lines in upserts.sql: $TOTAL_LINES"

        # D1 can handle ~50K statements per import before hitting memory limits
        CHUNK_SIZE=50000

        if [ "$TOTAL_LINES" -le "$CHUNK_SIZE" ]; then
          # Small file - import directly
          echo "Importing directly (small file)..."
          npx wrangler d1 execute ${{ inputs.database-name }} \
            --remote \
            --file="$UPSERTS_FILE"
        else
          # Large file - split and import in chunks
          echo "Large file detected. Splitting into chunks of $CHUNK_SIZE lines..."
          mkdir -p ${{ inputs.diff-path }}/chunks

          # Split file (skip comment lines for accurate chunking)
          grep -v '^--' "$UPSERTS_FILE" | split -l $CHUNK_SIZE - "${{ inputs.diff-path }}/chunks/chunk_"

          CHUNK_NUM=1
          TOTAL_CHUNKS=$(ls ${{ inputs.diff-path }}/chunks/chunk_* | wc -l)

          for chunk in ${{ inputs.diff-path }}/chunks/chunk_*; do
            echo "Importing chunk $CHUNK_NUM of $TOTAL_CHUNKS..."
            npx wrangler d1 execute ${{ inputs.database-name }} \
              --remote \
              --file="$chunk"
            CHUNK_NUM=$((CHUNK_NUM + 1))
          done

          echo "All chunks imported successfully."
        fi

    - name: Apply deletes
      if: inputs.has-changes == 'true'
      shell: bash
      run: |
        echo "Applying deletes to ${{ inputs.database-name }}..."
        npx wrangler d1 execute ${{ inputs.database-name }} \
          --remote \
          --file=${{ inputs.diff-path }}/deletes.sql

    - name: Update metadata
      if: inputs.has-changes == 'true'
      shell: bash
      run: |
        echo "Updating metadata for ${{ inputs.database-name }}..."
        npx wrangler d1 execute ${{ inputs.database-name }} \
          --remote \
          --file=${{ inputs.diff-path }}/metadata.sql
